version: "3.4"

services:
  extrabotts:
    image: extrabotts
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    networks:
      - extrabotts_default

  database:
    image: "mongo"
    container_name: "mongo-db"
    env_file: .env
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db/mongo-volume:/data/db
    networks:
      - extrabotts_default

networks:
  extrabotts_default:
    driver: bridge
